import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import os from 'node:os';import path from 'node:path';
import {PaperLedger,fingerprint} from './paper-ledger.mjs';
import {spawn} from 'node:child_process';
const policy={kind:'fixture',version:'ISOLATED-TEST-ONLY-v1',max_leverage:2,risk_per_trade:1000,max_funding_cost_fraction:0.01,holding_horizon_intervals:2,max_notional:1000,fee_fraction:0.001,slippage_fraction:0.001};
const owner={authenticated:true,subject:'fixture-owner'}, other={authenticated:true,subject:'fixture-other'};
function setup(t){const dir=mkdtempSync(path.join(os.tmpdir(),'paper-isolated-'));const filename=path.join(dir,'fixture-ledger.sqlite');let now=Date.now();const approvals=new Map();const verifyApproval=({approval,owner,binding,policy_version,now})=>{const a=approvals.get(approval);return !!a&&a.owner===owner&&a.binding===binding&&a.policy_version===policy_version&&a.expires>now;};const l=new PaperLedger({filename,namespace:'fixture',policy,verifyApproval,now:()=>now});t.after(()=>{l.close();rmSync(dir,{recursive:true,force:true});});let n=0;const state=()=>({perp:{source:'blofin_public',instrument_class:'crypto_perp',state:'fresh',generated_at:new Date(now).toISOString(),ttl_seconds:30,rows:[{symbol:'BTC-USDT',state:'fresh',mark:100,bid:99,ask:101,funding_rate:0.001,observed_at_ms:now}]}});const draft={mode:'paper',instrument_class:'crypto_perp',symbol:'BTC-USDT',side:'buy',type:'market',quantity:1,price:null,leverage:1,risk_amount:500,policy_version:policy.version};const approve=d=>{const id='fixture-approval-'+(++n);approvals.set(id,{owner:owner.subject,binding:fingerprint(d),policy_version:policy.version,expires:now+10000});return id;};const run=(action,input,key='fixture-key-'+(++n),who=owner,s=state())=>l.transaction(who,key,action,input,s);const submit=(d=draft)=>run('submit',{draft:d,approval:approve(d)}).order;return{l,filename,run,submit,draft,approve,state,advance:()=>{now+=40000;}};}
test('submit → partial → full fill → position → reduce → close; persisted history and P&L',t=>{const x=setup(t),o=x.submit();assert.equal(o.status,'pending');x.run('fill',{id:o.id,quantity:0.4});assert.equal(x.l.view(owner).orders[0].status,'partial');x.run('fill',{id:o.id,quantity:0.6});let p=x.l.view(owner).positions[0];assert.equal(p.quantity,1);x.run('reduce',{id:p.id,quantity:0.25});x.run('reduce',{id:p.id,quantity:0.75});p=x.l.view(owner).positions[0];assert.equal(p.status,'closed');assert.ok(p.realized_pnl<0);assert.equal(x.l.view(owner).history.length,5);const second=new PaperLedger({filename:x.filename,namespace:'fixture',policy});assert.equal(second.view(owner).positions[0].status,'closed');second.close();});
test('pending cancel and partial cancel preserve filled position; filled order cannot cancel',t=>{const x=setup(t),o=x.submit();x.run('cancel',{id:o.id});assert.throws(()=>x.run('fill',{id:o.id,quantity:1}),/order_not_fillable/);const p=x.submit();x.run('fill',{id:p.id,quantity:0.3});const c=x.run('cancel',{id:p.id});assert.equal(c.cancelled_quantity,0.7);assert.equal(x.l.view(owner).positions[0].quantity,0.3);const full=x.submit();x.run('fill',{id:full.id,quantity:1});assert.throws(()=>x.run('cancel',{id:full.id}),/cannot_cancel/);});
test('idempotency duplicates, changed payload and consumed approval',t=>{const x=setup(t),input={draft:x.draft,approval:x.approve(x.draft)};const a=x.run('submit',input,'duplicate-key');assert.equal(x.run('submit',input,'duplicate-key').order.id,a.order.id);assert.equal(x.l.view(owner).orders.length,1);assert.throws(()=>x.run('submit',{...input,draft:{...x.draft,quantity:2}},'duplicate-key'),/idempotency_conflict/);assert.throws(()=>x.run('submit',input),/approval_already_used/);});
test('invalid, oversized, nonfinite, stale, funding, wrong source and policy cases',t=>{const x=setup(t);for(const patch of [{quantity:0},{quantity:-1},{quantity:Infinity},{quantity:1e20},{quantity:20},{leverage:3},{risk_amount:1001},{risk_amount:1},{policy_version:'old'},{mode:'live'},{instrument_class:'crypto_spot'},{architect_authorized:true}])assert.throws(()=>x.submit({...x.draft,...patch}));for(const patch of [{state:'stale'},{source:'TradingView'},{generated_at:'bad'},{generated_at:new Date(Date.now()-60000).toISOString()}]){const s=x.state();Object.assign(s.perp,patch);assert.throws(()=>x.run('submit',{draft:x.draft,approval:x.approve(x.draft)},undefined,owner,s));}for(const funding_rate of [null,NaN,1]){const s=x.state();s.perp.rows[0].funding_rate=funding_rate;assert.throws(()=>x.run('submit',{draft:x.draft,approval:x.approve(x.draft)},undefined,owner,s));}x.l.policy=null;assert.throws(()=>x.submit(),/risk_policy_unset/);});
test('unauthenticated, forged, wrong-owner, expired, changed-draft approval all denied',t=>{const x=setup(t);assert.throws(()=>x.run('submit',{},undefined,null),/authentication_required/);assert.throws(()=>x.run('submit',{draft:x.draft,approval:'forged'}),/per_trade_approval_required/);const token=x.approve(x.draft);assert.throws(()=>x.run('submit',{draft:x.draft,approval:token},undefined,other),/per_trade_approval_required/);assert.throws(()=>x.run('submit',{draft:{...x.draft,quantity:2},approval:token}),/per_trade_approval_required/);x.advance();assert.throws(()=>x.run('submit',{draft:x.draft,approval:token}),/per_trade_approval_required/);const o=x.submit();for(const action of ['cancel','fill'])assert.throws(()=>x.run(action,action==='cancel'?{id:o.id}:{id:o.id,quantity:1},undefined,other),/order_not_found/);x.run('fill',{id:o.id,quantity:1});const p=x.l.view(owner).positions[0];assert.throws(()=>x.run('reduce',{id:p.id,quantity:1},undefined,other),/position_not_found/);assert.equal(x.l.view(other).history.length,0);});
test('both race serializations: cancel-before-fill, fill-before-cancel, close-before-later-partial-fill',t=>{const x=setup(t),a=x.submit();x.run('cancel',{id:a.id});assert.throws(()=>x.run('fill',{id:a.id,quantity:1}));const b=x.submit();x.run('fill',{id:b.id,quantity:1});assert.throws(()=>x.run('cancel',{id:b.id}));const c=x.submit();x.run('fill',{id:c.id,quantity:0.5});const p=x.l.view(owner).positions.find(p=>p.order_id===c.id);x.run('reduce',{id:p.id,quantity:0.5});x.run('fill',{id:c.id,quantity:0.5});assert.equal(x.l.view(owner).positions.find(v=>v.id===p.id).quantity,0.5);});
test('limit is never filled through its price; live actions always rejected',t=>{const x=setup(t),o=x.submit({...x.draft,type:'limit',price:95});assert.throws(()=>x.run('fill',{id:o.id,quantity:1}),/limit_not_marketable/);for(const action of ['live','order','broker','withdraw'])assert.throws(()=>x.run(action,{}),/unsupported_or_live_route_disabled/);});
test('fixture policy and ledger cannot cross operational namespace',t=>{const x=setup(t);assert.throws(()=>new PaperLedger({filename:x.filename,namespace:'operational',policy}),/fixture_policy_isolation/);assert.throws(()=>new PaperLedger({filename:x.filename,namespace:'operational'}),/ledger_namespace_mismatch/);});
test('settle replay after fill returns same receipt; forged fill fields denied',t=>{const x=setup(t),o=x.submit();const result=x.run('settle',{id:o.id},'settle-retry-key');assert.equal(result.order.status,'filled');const replay=x.run('settle',{id:o.id},'settle-retry-key');assert.equal(replay.duplicate,true);assert.equal(x.l.view(owner).history.length,2);assert.throws(()=>x.run('settle',{id:o.id,price:1}),/unsupported_fields/);});
test('decimal quantities reconcile exactly and excess representation precision is rejected',t=>{const x=setup(t),o=x.submit({...x.draft,quantity:0.3});x.run('fill',{id:o.id,quantity:0.1});x.run('fill',{id:o.id,quantity:0.2});assert.equal(x.l.view(owner).orders[0].status,'filled');const p=x.l.view(owner).positions[0];x.run('reduce',{id:p.id,quantity:0.1});x.run('reduce',{id:p.id,quantity:0.2});assert.equal(x.l.view(owner).positions[0].status,'closed');assert.throws(()=>x.submit({...x.draft,quantity:0.123456789}),/invalid_values/);});
test('stale quote prevents fill/reduce without changing ledger; cancel needs no price',t=>{const x=setup(t),o=x.submit();const stale=x.state();stale.perp.rows[0].observed_at_ms-=60000;const before=JSON.stringify(x.l.view(owner));assert.throws(()=>x.run('fill',{id:o.id,quantity:1},undefined,owner,stale),/stale/);assert.equal(JSON.stringify(x.l.view(owner)),before);x.run('fill',{id:o.id,quantity:1});const p=x.l.view(owner).positions[0];assert.throws(()=>x.run('reduce',{id:p.id,quantity:1},undefined,owner,stale),/stale/);const a=x.submit();assert.equal(x.run('cancel',{id:a.id},undefined,owner,stale).order.status,'cancelled');});
test('separate-process simultaneous fill/cancel and double-close serialize atomically',async t=>{
 const x=setup(t),o=x.submit();
 const worker=(action,input,key)=>new Promise((resolve,reject)=>{
  const source=`import {PaperLedger} from ${JSON.stringify(new URL('./paper-ledger.mjs',import.meta.url).href)};const l=new PaperLedger({filename:${JSON.stringify(x.filename)},namespace:'fixture',policy:${JSON.stringify(policy)}});process.send('ready');process.once('message',()=>{try{l.transaction(${JSON.stringify(owner)},${JSON.stringify(key)},${JSON.stringify(action)},${JSON.stringify(input)},${JSON.stringify(x.state())});console.log('committed')}catch(e){console.log('refused:'+e.message)}finally{l.close();process.disconnect()}})`;
  const p=spawn(process.execPath,['--input-type=module','-e',source],{stdio:['ignore','pipe','pipe','ipc']});let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('message',()=>resolve({start:()=>p.send('go'),done:new Promise((ok,no)=>p.on('exit',code=>code?no(Error(err)):ok(out.trim())))}));
 });
 const race=async specs=>{const workers=await Promise.all(specs.map(s=>worker(...s)));workers.forEach(w=>w.start());return Promise.all(workers.map(w=>w.done));};
 const outcomes=await race([['fill',{id:o.id,quantity:1},'race-fill-key'],['cancel',{id:o.id},'race-cancel-key']]);
 assert.equal(outcomes.filter(x=>x==='committed').length,1);assert.ok(['filled','cancelled'].includes(x.l.view(owner).orders[0].status));
 const b=x.submit();x.run('fill',{id:b.id,quantity:1});const p=x.l.view(owner).positions.find(p=>p.order_id===b.id);
 const closes=await race([['reduce',{id:p.id,quantity:1},'race-close-key-a'],['reduce',{id:p.id,quantity:1},'race-close-key-b']]);
 assert.equal(closes.filter(x=>x==='committed').length,1);assert.equal(x.l.view(owner).positions.find(v=>v.id===p.id).quantity,0);
});
