const {test,expect}=require('@playwright/test');const path=require('node:path');
test.beforeEach(async({context})=>{await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin==='http://127.0.0.1:5197')return r.continue();return r.abort();});});
async function desk(page){await page.goto('/?page=trading');await page.waitForLoadState('networkidle');const hide=page.getByRole('button',{name:'Hide sidebar'});if(await hide.isVisible())await hide.click();await page.getByRole('button',{name:'Paper workspace',exact:true}).click();await expect(page.getByText(/ISOLATED FIXTURE POLICY/)).toBeVisible();}
async function ticket(page,qty='1'){await page.getByLabel('Quantity',{exact:true}).fill(qty);await page.getByLabel('Leverage',{exact:true}).fill('1');await page.getByLabel('Risk reserve (USDT)').fill('500');await page.getByLabel('Confirm this specific PAPER ticket').check();}
test('chart selectors are display-only and cannot change a paper ticket',async({page},info)=>{
 await desk(page);await page.getByLabel('Chart symbol — display only').fill('NASDAQ:MSFT');await page.getByRole('button',{name:'Apply chart symbol'}).click();await page.getByRole('combobox',{name:'Chart interval',exact:true}).selectOption('60');
 const frame=page.locator('iframe[title="TradingView third-party chart"]');const src=await frame.getAttribute('src');const config=JSON.parse(decodeURIComponent(new URL(src).hash.slice(1)));expect(config.symbol).toBe('NASDAQ:MSFT');expect(config.interval).toBe('60');expect(await page.getByRole('combobox',{name:'Perpetual symbol',exact:true}).inputValue()).toBe('BTC-USDT');
 await page.getByLabel('Chart symbol — display only').fill('<script>');await page.getByRole('button',{name:'Apply chart symbol'}).click();await expect(page.getByText('Use a TradingView display symbol in EXCHANGE:TICKER format.')).toBeVisible();await page.locator('.tradingview-surface').screenshot({path:path.resolve('../evidence/'+info.project.name+'-chart-selector.png')});
});
test('operational policy missing stays unset in the UI; no fixture values populate policy setup',async({page},info)=>{
 await page.route('**/api/trading/paper/status',r=>r.fulfill({json:{mode:'paper',namespace:'operational',policy:null,admission:false}}));await page.route('**/api/trading/paper/ledger',r=>r.fulfill({status:409,json:{error:'risk_policy_unset'}}));
 await page.goto('/?page=trading');await page.getByRole('button',{name:'Paper workspace',exact:true}).click();await expect(page.getByText(/OPERATIONAL POLICY UNSET/)).toBeVisible();await expect(page.getByText(/Admission held: configure/)).toBeVisible();await page.getByText('Risk policy setup — validate only, never activate defaults',{exact:true}).click();expect(await page.getByLabel('Leverage cap',{exact:true}).inputValue()).toBe('');await page.locator('.trading-workspace').screenshot({path:path.resolve('../evidence/'+info.project.name+'-operational-unset.png')});
});
test('actual candidate UI: submit, simulated fill, reduce, close, cancel and history',async({page},info)=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await desk(page);await ticket(page);await page.getByRole('button',{name:'Confirm & submit paper trade'}).click();await expect(page.getByRole('button',{name:'Simulate eligible fill'}).last()).toBeVisible();await page.locator('.trading-workspace').screenshot({path:path.resolve('../evidence/'+info.project.name+'-pending-controls.png')});await page.getByRole('button',{name:'Simulate eligible fill'}).last().click();await expect(page.getByRole('button',{name:'Close position'}).last()).toBeVisible();await page.locator('.trading-workspace').screenshot({path:path.resolve('../evidence/'+info.project.name+'-position-controls.png')});await page.getByLabel('Reduce quantity BTC-USDT').last().fill('0.25');await page.getByRole('button',{name:'Reduce position',exact:true}).last().click();await expect(page.getByText('Quantity 0.75 · Average entry', {exact:false})).toBeVisible();await page.getByRole('button',{name:'Close position',exact:true}).last().click();await expect(page.getByRole('button',{name:'Close position',exact:true})).toHaveCount(0);await ticket(page);await page.getByRole('button',{name:'Confirm & submit paper trade'}).click();await page.getByRole('button',{name:'Cancel remaining quantity'}).last().click();await expect(page.getByRole('button',{name:'Cancel remaining quantity'})).toHaveCount(0);await expect(page.locator('[aria-label="Paper controls"]')).toContainText('cancel');await page.locator('.trading-workspace').screenshot({path:path.resolve('../evidence/'+info.project.name+'-paper-controls.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);});
test('negative UI: oversized ticket refused; changing ticket clears confirmation',async({page},info)=>{await desk(page);await ticket(page,'20');await page.getByRole('button',{name:'Confirm & submit paper trade'}).click();await expect(page.getByRole('alert')).toContainText('oversize notional');await page.getByLabel('Quantity',{exact:true}).fill('1');await expect(page.getByLabel('Confirm this specific PAPER ticket')).not.toBeChecked();await page.locator('.trading-workspace').screenshot({path:path.resolve('../evidence/'+info.project.name+'-paper-negative.png')});});
test('HTTP negative boundaries, no real-money calls even in tests',async({request})=>{for(const endpoint of ['live','order','broker','paper/live']){const r=await request.post('/api/trading/'+endpoint,{data:{mode:'live',architect_authorized:true}});expect(r.status()).toBe(404);}expect((await request.get('/api/trading/paper/ledger',{headers:{'x-fixture-unauthenticated':'1'}})).status()).toBe(401);expect((await request.post('/api/trading/paper/submit',{headers:{'Idempotency-Key':'forged-request'},data:{draft:{mode:'paper',instrument_class:'crypto_perp',symbol:'BTC-USDT',side:'buy',type:'market',quantity:1,price:null,leverage:1,risk_amount:500,policy_version:'ISOLATED-TEST-ONLY-v1'},approval:'forged'}})).status()).toBe(403);expect((await request.post('/api/trading/paper/cancel',{headers:{Origin:'https://untrusted.invalid'},data:{id:'none'}})).status()).toBe(403);});
